markdown: kramdown

repository: https://github.com/kristapsm/adop-pluggable-scm

collections:
  docs:
      output: true

exclude: [ vendor README.md Gemfile Gemfile.lock Dockerfile docker-compose.yml ]

title: ADOP
description: 
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman